sudo: required
dist: trusty
stages:
  - test
  - lint
language: python
python:
  - "2.7"
  - "3.6"
env:
  - COMPONENT=knn
install:
- cd $COMPONENT
- ls
- sudo apt-get install python-scipy
- pip install -r requirements.py
script:
- pytest
git:
  depth:
    3
jobs:
  include:
  - stage: lint
    env:
    language: python
    python: 3.6
    install:
    - pip install pylint
    script:
    - pylint 
